services:
  - type: web
    name: atenea-web
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn atenea.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: USE_SQLITE
        value: False
      - key: ALLOWED_HOSTS
        value: atenea-web.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: POSTGRES_DB
        value: atenea
      - key: POSTGRES_USER
        value: atenea
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: atenea-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: atenea-db
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: atenea-db
          property: connectionString
      - key: GCS_BUCKET_NAME
        value: devid-bucket-0001
      - key: GCS_PROJECT_ID
        value: proeduca-472312
      - key: HEYGEN_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        value: redis://redis-13128.c12.us-east-1-4.ec2.redns.redis-cloud.com:13128
      - key: REDIS_PASSWORD
        sync: false

  - type: pserv
    name: atenea-db
    env: postgresql
    plan: starter
    region: oregon
